name: py-release

# gh workflow run py-release
# This also runs on release deploy
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      
      - name: Upload
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          sudo apt install libssl-dev
          sudo apt install pkg-config
          pip install maturin[patchelf]==1.4.0 twine
          python3 -m venv venv
          source venv/bin/activate
          cd mistralrs-pyo3
          python3 upload.py
